version: 0.2

phases:
  install:
    commands:
      - git config --global credential.helper '!aws --region us-east-1 codecommit credential-helper $@'
      - git config --global credential.UseHttpPath true
  pre_build:
    commands:
  build:
    commands:
      - zip lambda_function.zip lambda_function.py
      - aws lambda update-function-code --function-name python-config --zip-file file://lanbda_function.zip
  post_build:
    commands:
